uc-cdis/gitops-dev

- abby.planx-pla.net/manifest.json
- andrew.planx-pla.net/manifest.json
- avantol.planx-pla.net/manifest.json
- bjr.planx-pla.net/manifest.json
- dev.planx-pla.net/manifest.json
- giangb.planx-pla.net/manifest.json
- mlukowski.planx-pla.net/manifest.json
- pauline.planx-pla.net/manifest.json
- phillis.planx-pla.net/manifest.json
- qingya.planx-pla.net/manifest.json
- reuben.planx-pla.net/manifest.json
- rudyard.planx-pla.net/manifest.json
- steven.planx-pla.net/manifest.json
- thanhnd.planx-pla.net/manifest.json
- tsummer.planx-pla.net/manifest.json
- workflow.planx-pla.net/manifest.json
> fix(global): manifest.json has global block

- thanhnd.planx-pla.net/manifest.json
> chore(user-agreement): test user-agreement

- abby.planx-pla.net/manifest.json
- andrew.planx-pla.net/manifest.json
- avantol.planx-pla.net/manifest.json
- bjr.planx-pla.net/manifest.json
- dev.planx-pla.net/manifest.json
- fauziv1.planx-pla.net/manifest.json
- giangb.planx-pla.net/manifest.json
- mingfei.planx-pla.net/manifest.json
- mlukowski.planx-pla.net/manifest.json
- pauline.planx-pla.net/manifest.json
- phillis.planx-pla.net/manifest.json
- qingya.planx-pla.net/manifest.json
- reuben.planx-pla.net/manifest.json
- rudyard.planx-pla.net/manifest.json
- steven.planx-pla.net/manifest.json
- thanhnd.planx-pla.net/manifest.json
- tsummer.planx-pla.net/manifest.json
- workflow.planx-pla.net/manifest.json
- zakir.planx-pla.net/manifest.json
- zlchitty.planx-pla.net/manifest.json
* remove canary property and canary versions from all manifests
> refactor(manifest): remove canary services from all manifests

- thanhnd.planx-pla.net/etlMapping.yaml
> chore(etlmapping): add etlMapping for thanhnd

- raryav1.planx-pla.net/manifest.json
added manifest for raryav1.planx-pla.net
> chore(manifest):added for rarya

- rarya.planx-pla.net/manifest.json
- raryav1.planx-pla.net/manifest.json
> chore(manifest): add rarya hist

- mattgarvin1.planx-pla.net/manifest.json
> Fix json typo.

- abby.planx-pla.net/manifest.json
- andrew.planx-pla.net/manifest.json
- atharva.planx-pla.net/manifest.json
- avantol.planx-pla.net/manifest.json
- diwv1.planx-pla.net/manifest.json
- emalinowskiv1.planx-pla.net/manifest.json
- fauziv1.planx-pla.net/manifest.json
- giangb.planx-pla.net/manifest.json
- mattgarvin1.planx-pla.net/manifest.json
- mingfei.planx-pla.net/manifest.json
- mlukowski.planx-pla.net/manifest.json
- mpingram.planx-pla.net/manifest.json
- pauline.planx-pla.net/manifest.json
- qingya.planx-pla.net/manifest.json
- reuben.planx-pla.net/manifest.json
- thanhnd.planx-pla.net/manifest.json
- zakir.planx-pla.net/manifest.json
- zlchitty.planx-pla.net/manifest.json
* Pelican import job requires sheepdog creds for write access for now
> Credentials for Pelican import job

- mattgarvin1.planx-pla.net/manifest.json
Make mariner s3 backend configurable via manifest.
> Add user-data bucket to mariner config.

- hara.planx-pla.net/etlMapping.yaml
- hara.planx-pla.net/manifest.json
- hara.planx-pla.net/portal/gitops.json
> update hara commons config for latest release

- giangb.planx-pla.net/manifest.json
add sower job for manifest indexing job
> feat(manifest_indexing): gitops for manifest indexing service

- mattgarvin1.planx-pla.net/manifest.json
- increase mariner engine memory limit in Matt's dev env
> up mariner engine memory limit

- fauzi.planx-pla.net/etlMapping.yaml
- fauzi.planx-pla.net/manifest.json
> add(fauzi): dev

- fauzi.planx-pla.net/manifest.json
> chore(aws-es-proxy): bump version

- fauzi.planx-pla.net/manifest.json
- fauzi.planx-pla.net/portal/gitops.css
- fauzi.planx-pla.net/portal/gitops.default.json
- fauzi.planx-pla.net/portal/gitops.json
- Nothing in particular, just updates.
> updated manifest and portal

- dev.planx-pla.net/manifest.json
> v1.10.2-debian-cloudwatch-1.0

- tkrizzle.planx-pla.net/etlMapping.yaml
- tkrizzle.planx-pla.net/manifest.json
- tkrizzle.planx-pla.net/manifests/fence/fence-config-public.yaml
- tkrizzle.planx-pla.net/manifests/hatchery/.env
- tkrizzle.planx-pla.net/manifests/hatchery/.gitignore
- tkrizzle.planx-pla.net/manifests/hatchery/dicom-compose.yaml
- tkrizzle.planx-pla.net/manifests/hatchery/hatchery.json
- tkrizzle.planx-pla.net/manifests/hatchery/notebook-app.yaml
- tkrizzle.planx-pla.net/manifests/hatchery/test-app.yaml
- tkrizzle.planx-pla.net/manifests/scaling/scaling.json
- tkrizzle.planx-pla.net/portal/gitops.json
Added new dev env for tkrizzle
> feat(tkrizzle-env): Added new env for tkrizzle

- tkrizzle.planx-pla.net/manifest.json
- tkrizzle.planx-pla.net/portal/gitops.json
Setup manifest to pick up local config changes
> chore(gitops): update manifest

- giangb.planx-pla.net/manifest.json
> chore(dictionary): use dev dictionary

- mattgarvin1.planx-pla.net/manifest.json
- use mariner version 1.0.0, not latest commit from a dev branch
> revise mariner image tags to pull version 1.0.0

- mattgarvin1.planx-pla.net/manifest.json
- apply latest gen3fuse release tag to gen3fuse image in mariner config
> update gen3fuse image tag in mariner config

- giangb.planx-pla.net/manifest.json
Jira Ticket: [PXP-6666](https://ctds-planx.atlassian.net/browse/PXP-6666)
Add object indexing sower job
> feat(object_indexing): add object indexing config

- mattgarvin1.planx-pla.net/manifest.json
> fix envvar for k8s

- .secrets.baseline
- john.planx-pla.net/etlMapping.yaml
- john.planx-pla.net/manifest.json
- john.planx-pla.net/manifests/fence/fence-config-public.yaml
- john.planx-pla.net/manifests/hatchery/.env
- john.planx-pla.net/manifests/hatchery/.gitignore
- john.planx-pla.net/manifests/hatchery/dicom-compose.yaml
- john.planx-pla.net/manifests/hatchery/hatchery.json
- john.planx-pla.net/manifests/hatchery/notebook-app.yaml
- john.planx-pla.net/manifests/hatchery/test-app.yaml
- john.planx-pla.net/manifests/scaling/scaling.json
- john.planx-pla.net/portal/gitops.json
I missed this during onboarding. Add `john.planx-pla.net` commons.
> chore(john): add commons

- mattgarvin1.planx-pla.net/manifest.json
Matt's env - test Fence branch
> test branhc

- christopher.planx-pla.net/manifest.json
> chore(christopher): add dev env

- mattgarvin1.planx-pla.net/manifest.json
pin mariner version to write up demo for mariner K-T's
> pin latest mariner release

- fence.planx-pla.net/etlMapping.yaml
- fence.planx-pla.net/manifest.json
- fence.planx-pla.net/manifests/fence/fence-config-public.yaml
- fence.planx-pla.net/manifests/hatchery/.env
- fence.planx-pla.net/manifests/hatchery/.gitignore
- fence.planx-pla.net/manifests/hatchery/dicom-compose.yaml
- fence.planx-pla.net/manifests/hatchery/hatchery.json
- fence.planx-pla.net/manifests/hatchery/notebook-app.yaml
- fence.planx-pla.net/manifests/hatchery/test-app.yaml
- fence.planx-pla.net/manifests/scaling/scaling.json
- fence.planx-pla.net/portal/gitops.json
- fence.planx-pla.net/rsync.sh
adding fence.planx-pla.net to gitops-dev
> adding fence.planx-pla.net

- gomezmh.planx-pla.net/manifest.json
> Remove comment which has inval char :

- gomezmh.planx-pla.net/manifest.json
…dispatcher_job_num flag to manifest
> Added missing requirement for ssjdispatcher: added metadata service

- ramunerella.planx-pla.net/manifest.json
> updated indexs3 client info

- sai.planx-pla.net/manifest.json
Added a new dev directory called 'sai.planx-pla.net
> Added dev dir with name 'sai'

- fence.planx-pla.net/manifest.json
Update fence env to use brh user yaml
> update user yaml

- .secrets.baseline
- will.planx-pla.net/manifest.json
- will.planx-pla.net/metadata/aggregate_config.json
- will.planx-pla.net/portal/gitops.json
Jira Ticket: [HP-291](https://ctds-planx.atlassian.net/browse/HP-291), [HP-320](https://ctds-planx.atlassian.net/browse/HP-320)
* Start using the manifest to control metadata-service configs
> feat(metadata): metadata config changes

- hara.planx-pla.net/manifest.json
> update env to latest versions

- andrew.planx-pla.net/manifest.json
> fix(andrew): add metadata-service

- README.md
- andrew.planx-pla.net/manifest.json
- atharva.planx-pla.net/manifest.json
- avantol.planx-pla.net/manifest.json
- binamb.planx-pla.net/manifest.json
- brian.occ-pla.net/manifest.json
- ctds.workspace.planx-pla.net/manifest.json
- dev.planx-pla.net/manifest.json
- emalinowskiv1.planx-pla.net/manifest.json
- fauzi.planx-pla.net/manifest.json
- fauziv1.planx-pla.net/manifest.json
- fence.planx-pla.net/manifest.json
- galaxy.planx-pla.net/manifest.json
- georget.planx-pla.net/manifest.json
- gomezmh.planx-pla.net/manifest.json
- hara.planx-pla.net/manifest.json
- mingfei.planx-pla.net/manifest.json
- mlukowski.planx-pla.net/manifest.json
- pauline.planx-pla.net/manifest.json
- ramunerella.planx-pla.net/manifest.json
- sai.planx-pla.net/manifest.json
- thanhnd.planx-pla.net/manifest.json
- urvi.occ-pla.net/manifest.json
- yogeshk.planx-pla.net/manifest.json
- zuyi.planx-pla.net/manifest.json
Update fluentd to work with karpenter
> chore(fluentd-version): Updated fluentd versions for karpenter

- krishna.planx-pla.net/manifest.json
> Update manifest.json - updated audit-service version

- krishna.planx-pla.net/manifest.json
> Change for krishna manifest.json

- hara.planx-pla.net/manifest.json
Link to JIRA ticket if there is one:
> Update dev env

- hara.planx-pla.net/portal/gitops.json
Link to JIRA ticket if there is one:
> Update portal - hara

- atharva.planx-pla.net/etlMapping.yaml
- atharva.planx-pla.net/manifest.json
- atharva.planx-pla.net/manifests/hatchery/hatchery.json
- atharva.planx-pla.net/metadata/aggregate_config.json
- atharva.planx-pla.net/portal/gitops.json
Link to JIRA ticket if there is one:
> Update Atharva dev env

- .pre-commit-config.yaml
- .secrets.baseline
- hara.planx-pla.net/manifests/hatchery/hatchery.json
Link to JIRA ticket if there is one:
> Update hara - add workspace

- binamb.planx-pla.net/manifests/hatchery/hatchery.json
adding hatchery configuration to binamb's dev environment
> adding hatchery configuration to binamb's dev environment
